import React from "react";

function Privacy_Policy() {
  return (
    <div>
      <h1>Privacy Policy</h1>
      <p>
        Kamdhenuseva.com is committed to protecting your privacy. This Privacy
        Policy explains how your personal information is collected, used, and
        disclosed by Kamdhenuseva.com.
      </p>
      <p>
        This Privacy Policy applies to our website, and its associated
        subdomains (collectively, our “Service”) alongside our application,
        Kamdhenuseva.com. By accessing or using our Service, you signify that
        you have read, understood, and agree to our collection, storage, use,
        and disclosure of your personal information as described in this Privacy
        Policy and our Terms of Service.
      </p>
      <div>
        <h3>Definitions and key terms</h3>
        <p>
          To help explain things as clearly as possible in this Privacy Policy,
          every time any of these terms are referenced, are strictly defined as:
        </p>
        <span>Cookie:</span>
        <p>
          small amount of data generated by a website and saved by your web
          browser. It is used to identify your browser, provide analytics,
          remember information about you such as your language preference or
          login information.
        </p>
      </div>
    </div>
  );
}

export default Privacy_Policy;
