import React from "react";
import './Privacy_Policy.css'

function Privacy_Policy() {
  return (
    <div className="Policy">
      <h1>Privacy Policy</h1>
      <div className="head_para">
        <p>
          Kamdhenuseva.com is committed to protecting your privacy. This Privacy
          Policy explains how your personal information is collected, used, and
          disclosed by Kamdhenuseva.com.
        </p>
        <p>
          This Privacy Policy applies to our website, and its associated
          subdomains (collectively, our “Service”) alongside our application,
          Kamdhenuseva.com. By accessing or using our Service, you signify that
          you have read, understood, and agree to our collection, storage, use,
          and disclosure of your personal information as described in this Privacy
          Policy and our Terms of Service.
        </p>
      </div>
      <div className="Key-section">
        <h3>Definitions and key terms</h3>
        <p>
          To help explain things as clearly as possible in this Privacy Policy,
          every time any of these terms are referenced, are strictly defined as:
        </p>
        <p>
          Cookie: small amount of data generated by a website and saved by your
          web browser. It is used to identify your browser, provide analytics,
          remember information about you such as your language preference or
          login information.
        </p>
        <p>
          Company: when this policy mentions “Company,” “we,” “us,” or “our,” it
          refers to Shri Devraha Baba Gauseva Sansthan Trust Dangoli Banger
          Thana – Mat, (Yogiraj Devraha Baba, Panigaon Khader, Vrindavan, Uttar
          Pradesh 281121), that is responsible for your information under this
          Privacy Policy.
        </p>
        <p>Country: where Kamdhenuseva.com or the owners/founders of Kamdhenuseva.com are based, in this case is India</p>
        <p>Customer: refers to the company, organization or person that signs up to use the Kamdhenuseva.com Service to manage the relationships with your consumers or service users.</p>
        <p>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Kamdhenuseva.com and use the services.</p>
        <p>IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</p>
        <p>Personnel: refers to those individuals who are employed by Kamdhenuseva.com or are under contract to perform a service on behalf of one of the parties.</p>
        <p>Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</p>
        <p>Service: refers to the service provided by Kamdhenuseva.com as described in the relative terms (if available) and on this platform. </p>
        <p>Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</p>
        <p>Website: Kamdhenuseva.com’s site, which can be accessed via this URL: https://kamdhenuseva.com/</p>
        <p>You: a person or entity that is registered with Kamdhenuseva.com to use the Services.</p>
        <h3>What Information Do We Collect?</h3>
        <p><strong>We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</strong></p>
        <p>Name / Username</p>
        <p>Phone Numbers</p>
        <p>Email Addresses</p>
        <p>Billing Addresses</p>
        <p>Debit/credit card numbers</p>
        <h3>When does Kamdhenuseva.com use end user information from third parties?</h3>
        <p>Kamdhenuseva.com will collect End User Data necessary to provide the Kamdhenuseva.com services to our customers. End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>
        <h3>When does Kamdhenuseva.com use customer information from third parties?</h3>
        <p>We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Kamdhenuseva.com customer, we receive information from a third party that provides automated fraud detection services to Kamdhenuseva.com. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings</p>
        <h3>Do we share the information we collect with third parties?</h3>
        <p>We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.</p>
        <p>We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.</p>
      </div>
    </div>
  );
}

export default Privacy_Policy;
